name: 'CD Action'
description: 'Builds and pushes Docker image to ECR'
env:
  ECR_REPOSITORY: analyticsamd
  IMAGE_TAG: latest
runs:
  using: 'composite'  # Use composite to run multiple steps
  steps:
    - name: Build and Push Docker image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
          --push \
          .
        echo "Image built and pushed to ECR"
      shell: bash