name: 'CI Action'
description: 'Runs tests and linting for the project'
runs:
  using: 'composite'
  steps:
    - name: Run tests with coverage
      run: pytest --cov=app --cov-report=term-missing --cov-report=xml --cov-fail-under=85 tests/
      shell: bash

    - name: Run linting
      run: flake8 app/ --count --show-source --statistics
      shell: bash

    - name: Upload coverage report
      run: |
        echo "Uploading coverage report"
        cp coverage.xml $GITHUB_WORKSPACE/