openapi: 3.0.0
info:
  title: Analytics API
  description: API for calculating analytics based on datasets
  version: 1.0.0
paths:
  /predict:
    post:
      summary: Predict values using linear regression
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictionRequest'
      responses:
        '200':
          description: Successful prediction
        '400':
          description: Bad request
  /average-price-by-suburb:
    post:
      summary: Calculate the average price per suburb
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FilteredEventData'
      responses:
        '200':
          description: Average prices per suburb
        '400':
          description: Bad request
  /median-price-by-suburb:
    post:
      summary: Calculate the median price per suburb
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FilteredEventData'
      responses:
        '200':
          description: Median prices per suburb
        '400':
          description: Bad request
  /highest-value:
    post:
      summary: Find the highest value of an attribute
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
      responses:
        '200':
          description: Highest value found
        '400':
          description: Bad request
  /lowest-value:
    post:
      summary: Find the lowest value of an attribute
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
      responses:
        '200':
          description: Lowest value found
        '400':
          description: Bad request
  /median-value:
    post:
      summary: Find the median value of an attribute
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
      responses:
        '200':
          description: Median value found
        '400':
          description: Bad request
  /predict-future-prices:
    post:
      summary: Predict future prices using linear regression
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FuturePrices'
      responses:
        '200':
          description: Predicted future prices
        '400':
          description: Bad request
  /price-outliers:
    post:
      summary: Identify outlier prices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FilteredEventData'
      responses:
        '200':
          description: List of outliers
        '400':
          description: Bad request
  /total-sales-per-year:
    post:
      summary: Calculate total sales per year
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FilteredEventData'
      responses:
        '200':
          description: Total sales per year
        '400':
          description: Bad request
  /most-expensive-and-cheapest-suburb:
    post:
      summary: Find the most expensive and cheapest suburb
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FilteredEventData'
      responses:
        '200':
          description: Most expensive and cheapest suburb
        '400':
          description: Bad request
components:
  schemas:
    FilteredEventData:
      type: object
      properties:
        time_object:
          type: object
          additionalProperties: true
        event_type:
          type: string
        attribute:
          type: object
          additionalProperties: true
    PredictionRequest:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/FilteredEventData'
        x_attribute:
          type: string
        y_attribute:
          type: string
        x_values:
          type: array
          items:
            type: string
    RequestBody:
      type: object
      properties:
        attribute_name:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/FilteredEventData'
    FuturePrices:
      type: object
      properties:
        years:
          type: array
          items:
            type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/FilteredEventData'
