name: Build and Push to AWS ECR

on:
  push:
    branches:
      - main
      - setup_CD

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: analyticsamd
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build AMD64 Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --push \
            .
          echo "Image built and pushed to ECR"
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run unit tests with coverage
        run: |
          pytest --cov=app --cov-report=html --cov-report=xml --cov-fail-under=85 --junitxml=report.xml tests

      - name: Verify coverage report directory
        run: |
          if [ ! -d "htmlcov" ]; then
            echo "Error: htmlcov/ directory not found. Ensure tests pass and --cov-report=html is enabled."
            exit 1
          fi

      - name: Upload coverage report
        uses: actions/upload-pages-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

  