name: Analytics CI/CD

on:
  push:
    branches:
      - main
      - setup_CI
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CI steps
        uses: ./.github/actions/action-ci  # Correct path to the local action

  continuous_deployment:
    runs-on: ubuntu-latest
    needs: continuous_integration  # Ensure this job runs only after CI succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Run CD steps
        uses: ./.github/actions/action-cd  # Correct path to the local action