name: Analytics CI/CD

on:
  push:
    branches:
      - main
      - setup_CI
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    uses: W18BTANGO/ci-cd/.github/workflows/integrate.yaml@main

  deploy:
    uses:  W18BTANGO/ci-cd/.github/workflows/deploy.yaml@main
    with:
      aws-region: ap-southeast-2                        
      ecr-repository: analyticsamd                      
      ecs-service: analyticsEC2service                  
      ecs-cluster: AnalyticsClusterEC2                  
      ecs-task-definition: .aws/td2-amd-revision2.json                      
      container-name: analyticsamd                     
                                                       
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # continuous_deployment:
  #   runs-on: ubuntu-latest
  #   needs: continuous_integration
  #   env:
  #     AWS_REGION: ap-southeast-2
  #     ECR_REPOSITORY: analyticsamd
  #     IMAGE_TAG: latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run CD steps
  #       uses: ./.github/actions/action-cd
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}